name: "Hypon Cloud"
description: "Integrate Hypon Cloud with Home Assistant"
url: "https://github.com/amckee23/home-assistant-hypon-cloud"
version: "1.2.0"
slug: "hypon_cloud_integration"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
hassio_role: homeassistant
stdin: true
init: false
options:
  username: "change_me"
  password: "change_me"
  refresh_time: 300
  system_id: "change_me"
  enable_time_mode_config: false
  inverter_sn: ""
  config_put_endpoint: "/inverter/config"
  config_put_method: "PUT"
  timemode: 0
  timepower: 100
  timestarttime: "03:30"
  timeendtime: "05:30"
  time_enable: 1
  old_time_enable: 0
  timen: 1
  timeweekday1: 1
  timeweekday2: 1
  timeweekday3: 1
  timeweekday4: 1
  timeweekday5: 1
  timeweekday6: 1
  timeweekday7: 1
schema:
  username: str
  password: password
  system_id: str
  refresh_time: int(60,3600)
  enable_time_mode_config: bool
  inverter_sn: str
  config_put_endpoint: str
  config_put_method: str
  timemode: int(0,1)
  timepower: int(0,10000)
  timestarttime: str
  timeendtime: str
  time_enable: int(0,1)
  old_time_enable: int(0,1)
  timen: int(1,10)
  timeweekday1: int(0,1)
  timeweekday2: int(0,1)
  timeweekday3: int(0,1)
  timeweekday4: int(0,1)
  timeweekday5: int(0,1)
  timeweekday6: int(0,1)
  timeweekday7: int(0,1)